// pachinko/data.js — 共有データ（全ページから読み込む）

const STATIONS = [
  { id: "chiba",             ja: "千葉" },
  { id: "nishi-chiba",       ja: "西千葉" },
  { id: "inage",             ja: "稲毛" },
  { id: "shin-kemigawa",     ja: "新検見川" },
  { id: "makuhari",          ja: "幕張" },
  { id: "makuhari-hongo",    ja: "幕張本郷" },
  { id: "tsudanuma",         ja: "津田沼" },
  { id: "higashi-funabashi", ja: "東船橋" },
  { id: "funabashi",         ja: "船橋" },
  { id: "nishi-funabashi",   ja: "西船橋" },
  { id: "ichikawa",          ja: "市川" },
  { id: "hon-yawata",        ja: "本八幡" },
  { id: "koiwa",             ja: "小岩" },
  { id: "shin-koiwa",        ja: "新小岩" },
  { id: "hirai",             ja: "平井" },
  { id: "kameido",           ja: "亀戸" },
  { id: "kinshicho",         ja: "錦糸町" },
  { id: "ryogoku",           ja: "両国" },
  { id: "asakusabashi",      ja: "浅草橋" },
  { id: "akihabara",         ja: "秋葉原" },
];

// station:最寄り駅 walk:徒歩分 exchange:交換率 hp:公式HP
// pworld:p-worldパス daidata:台データオンラインID site7:サイトセブンURL
// specialty:得意分野タグ events:イベント[{date,name}]
// hours:営業時間 total:総台数
const SHOPS = {
  // ===== 千葉エリア =====
  "ピーアーク千葉駅前店":        { station:"千葉",    walk:1,  exchange:"", hp:"", pworld:"chiba/p-ark-chiba2",      daidata:"100856", site7:"", specialty:[], events:[], hours:"", total:"" },
  "アミューズ千葉":              { station:"千葉",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"100711", site7:"", specialty:[], events:[], hours:"", total:"" },
  "キクヤ千葉店":                { station:"千葉",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"101340", site7:"", specialty:[], events:[], hours:"", total:"" },
  "やすだ稲毛駅前店":            { station:"稲毛",    walk:1,  exchange:"", hp:"", pworld:"chiba/yasuda-inage",        daidata:"203061", site7:"", specialty:[], events:[], hours:"", total:"" },
  "エスパス日拓稲毛駅前新館":    { station:"稲毛",    walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"100948", site7:"", specialty:[], events:[], hours:"", total:"" },
  "パールショップともえ稲毛長沼店":{ station:"稲毛",  walk:10, exchange:"", hp:"", pworld:"",                         daidata:"",       site7:"", specialty:[], events:[], hours:"", total:"" },
  "パラッツォ新検見川店":        { station:"新検見川", walk:3, exchange:"", hp:"", pworld:"",                         daidata:"100957", site7:"", specialty:[], events:[], hours:"", total:"" },
  "やすだ幕張店":                { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"chiba/yasuda-makuhari",     daidata:"203072", site7:"", specialty:[], events:[], hours:"", total:"" },
  "TOHO幕張店":                  { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"203071", site7:"", specialty:[], events:[], hours:"", total:"" },
  "アスワン幕張":                { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"203111", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ビックマーチ東習志野店":      { station:"幕張本郷", walk:10, exchange:"", hp:"", pworld:"",                        daidata:"",       site7:"", specialty:[], events:[], hours:"", total:"" },
  "PIA津田沼":                   { station:"津田沼",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203014", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ニュークラウン津田沼店":      { station:"津田沼",  walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"203012", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ミリオン習志野店":            { station:"津田沼",  walk:10, exchange:"", hp:"", pworld:"",                         daidata:"203131", site7:"", specialty:[], events:[], hours:"", total:"" },
  "パラッツォ船橋店":            { station:"船橋",    walk:3,  exchange:"", hp:"", pworld:"chiba/palazzo-funabashi",   daidata:"100815", site7:"", specialty:[], events:[], hours:"", total:"" },
  "第一プラザ船橋店":            { station:"船橋",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"",       site7:"", specialty:[], events:[], hours:"", total:"" },
  "アスワンFUNABASHI":           { station:"船橋",    walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203122", site7:"", specialty:[], events:[], hours:"", total:"" },
  "トワーズ船橋店":              { station:"船橋",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"203136", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ガイア西船橋店":              { station:"西船橋",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203145", site7:"", specialty:[], events:[], hours:"", total:"" },
  "西船スターダスト":            { station:"西船橋",  walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"101371", site7:"", specialty:[], events:[], hours:"", total:"" },
  "サンパレス本八幡":            { station:"本八幡",  walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"202999", site7:"", specialty:[], events:[], hours:"", total:"" },
  "本八幡UNO":                   { station:"本八幡",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203003", site7:"", specialty:[], events:[], hours:"", total:"" },
  "本八幡ZoRoN":                 { station:"本八幡",  walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"210248", site7:"", specialty:[], events:[], hours:"", total:"" },
  "サンラッキー市川店":          { station:"市川",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"202984", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ハップス市川駅前店":          { station:"市川",    walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"202990", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ニュー後楽園市川店":          { station:"市川",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"202989", site7:"", specialty:[], events:[], hours:"", total:"" },
  // ===== 東京エリア（総武線） =====
  "Dステーション新小岩":         { station:"新小岩",  walk:3,  exchange:"", hp:"", pworld:"tokyo/dstation-shinkoiwa", daidata:"",       site7:"", specialty:[], events:[], hours:"", total:"" },
  "エスパス1300新小岩北口駅前店":{ station:"新小岩",  walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"100260", site7:"", specialty:[], events:[], hours:"", total:"" },
  "プライム平井":                { station:"平井",    walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"101191", site7:"", specialty:[], events:[], hours:"", total:"" },
  "キコーナ平井店":              { station:"平井",    walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203374", site7:"", specialty:[], events:[], hours:"", total:"" },
  "新ガーデン亀戸店":            { station:"亀戸",    walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"203379", site7:"", specialty:[], events:[], hours:"", total:"" },
  "スパークル亀戸店":            { station:"亀戸",    walk:5,  exchange:"", hp:"", pworld:"",                         daidata:"203383", site7:"", specialty:[], events:[], hours:"", total:"" },
  "スーパーDステーション錦糸町": { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"",       site7:"", specialty:[], events:[], hours:"", total:"" },
  "みとやジャックポット錦糸町店":{ station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"204071", site7:"", specialty:[], events:[], hours:"", total:"" },
  "みとや錦糸町南口店":          { station:"錦糸町",  walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"101388", site7:"", specialty:[], events:[], hours:"", total:"" },
  "みとや錦糸町北口店":          { station:"錦糸町",  walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"101321", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ヒノマル錦糸町店":            { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"204070", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ヒノマル錦糸町店II":          { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"",                         daidata:"204072", site7:"", specialty:[], events:[], hours:"", total:"" },
  "ビッグアップル秋葉原店":      { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/big-apple",          daidata:"203631", site7:"", specialty:[], events:[], hours:"", total:"" },
  "アイランド秋葉原店":          { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/island",             daidata:"203632", site7:"", specialty:[], events:[], hours:"", total:"" },
  "秋葉原UNO":                   { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/2090uno",            daidata:"203634", site7:"", specialty:[], events:[], hours:"", total:"" },
  "エスパス日拓秋葉原駅前店":    { station:"秋葉原",  walk:1,  exchange:"", hp:"", pworld:"",                         daidata:"100928", site7:"", specialty:[], events:[], hours:"", total:"" },
  "サイバーパチンコ秋葉原昭和通り口店":{ station:"秋葉原", walk:3, exchange:"", hp:"", pworld:"",                    daidata:"203636", site7:"", specialty:[], events:[], hours:"", total:"" },
};

const DATA = {
  tokyo: {
    d1: ["秋葉原UNO"],
    d2: ["ビッグアップル秋葉原店","新ガーデン亀戸店"],
    d3: ["Dステーション新小岩","エスパス1300新小岩北口駅前店","キコーナ平井店","サイバーパチンコ秋葉原昭和通り口店","スーパーDステーション錦糸町"],
    d4: ["みとやジャックポット錦糸町店","みとや錦糸町南口店","みとや錦糸町北口店"],
    d5: [],
    d6: ["アイランド秋葉原店","エスパス日拓秋葉原駅前店","ビッグアップル秋葉原店"],
    d7: ["エスパス1300新小岩北口駅前店","エスパス日拓秋葉原駅前店","スパークル亀戸店","みとやジャックポット錦糸町店","みとや錦糸町南口店","みとや錦糸町北口店","秋葉原UNO"],
    d8: ["新ガーデン亀戸店"],
    d9: ["Dステーション新小岩","エスパス1300新小岩北口駅前店","キコーナ平井店","スーパーDステーション錦糸町"],
    d0: ["キコーナ平井店","ヒノマル錦糸町店","ヒノマル錦糸町店II","みとやジャックポット錦糸町店","みとや錦糸町南口店","みとや錦糸町北口店","新ガーデン亀戸店"],
    m1:[],m2:[],m3:[],m4:[],m5:[],m6:[],m7:[],m8:[],m9:[],m10:[],m11:[],m12:[],m13:[],m14:[],m15:[],m16:[],m17:[],m18:[],m19:[],m20:[],m21:[],m22:[],m23:[],m24:[],m25:[],m26:[],m27:[],m28:[],m29:[],m30:[],m31:[],
    w0:[],w1:[],w2:[],w3:[],w4:[],w5:[],
    w6: ["新ガーデン亀戸店"],
    nth_1_6:[],nth_2_6:[],nth_3_6:[],nth_4_6:[],nth_1_0:[],nth_2_0:[],nth_3_0:[],nth_1_1:[],nth_2_1:[],nth_3_1:[],nth_1_2:[],nth_2_2:[],nth_3_2:[],nth_1_3:[],nth_2_3:[],nth_3_3:[],nth_1_4:[],nth_2_4:[],nth_3_4:[],nth_1_5:[],nth_2_5:[],nth_3_5:[],
    last_0:[],last_1:[],last_2:[],last_3:[],last_4:[],last_5:[],last_6:[],
    zorome: ["アイランド秋葉原店","ビッグアップル秋葉原店"],
    md: ["アイランド秋葉原店","エスパス日拓秋葉原駅前店","ビッグアップル秋葉原店","新ガーデン亀戸店"]
  },
  chiba: {
    d1: ["アスワン幕張","アミューズ千葉","第一プラザ船橋店","本八幡UNO"],
    d2: ["パールショップともえ稲毛長沼店","パラッツォ新検見川店","パラッツォ船橋店"],
    d3: ["ガイア西船橋店","サンパレス本八幡","ビックマーチ東習志野店","ミリオン習志野店","やすだ幕張店"],
    d4: ["TOHO幕張店"],
    d5: ["PIA津田沼","ピーアーク千葉駅前店","やすだ稲毛駅前店","やすだ幕張店","ニュー後楽園市川店"],
    d6: ["トワーズ船橋店","パールショップともえ稲毛長沼店"],
    d7: ["PIA津田沼","アスワンFUNABASHI","アミューズ千葉","エスパス日拓稲毛駅前新館","キクヤ千葉店","やすだ幕張店","やすだ稲毛駅前店","西船スターダスト"],
    d8: ["ハップス市川駅前店","パラッツォ新検見川店","パラッツォ船橋店"],
    d9: ["ガイア西船橋店","ビックマーチ東習志野店","やすだ幕張店"],
    d0: [],
    m1: ["サンラッキー市川店"],
    m2:[],m3:[],m4:[],m5:[],m6:[],m7:[],m8:[],m9:[],m10:[],
    m11: ["PIA津田沼","第一プラザ船橋店"],
    m12: ["PIA津田沼"],
    m13:[],
    m14: ["TOHO幕張店"],
    m15:[],m16:[],m17:[],m18:[],m19:[],m20:[],
    m21: ["サンラッキー市川店","やすだ稲毛駅前店","やすだ幕張店","第一プラザ船橋店"],
    m22: ["やすだ稲毛駅前店","やすだ幕張店"],
    m23:[],m24:[],m25:[],m26:[],
    m27: ["ニュークラウン津田沼店"],
    m28:[],m29:[],m30:[],m31:[],
    w0:[],w1:[],w2:[],w3:[],w4:[],w5:[],w6:[],
    nth_1_6:[],nth_2_6:[],nth_3_2:[],nth_3_6:[],
    nth_1_0:[],nth_2_0:[],nth_3_0:[],nth_1_1:[],nth_2_1:[],nth_3_1:[],nth_1_3:[],nth_2_3:[],nth_3_3:[],nth_1_4:[],nth_2_4:[],nth_3_4:[],nth_1_5:[],nth_2_5:[],nth_3_5:[],nth_4_6:[],
    last_6:[],last_0:[],last_1:[],last_2:[],last_3:[],last_4:[],last_5:[],
    zorome: ["PIA津田沼","アスワン幕張","アミューズ千葉","エスパス日拓稲毛駅前新館","サンラッキー市川店","トワーズ船橋店"],
    md: ["PIA津田沼","アミューズ千葉","キクヤ千葉店","本八幡ZoRoN"]
  }
};
