// pachinko/data.js — 共有データ（全ページから読み込む）

const STATIONS = [
  { id: "chiba",             ja: "千葉" },
  { id: "nishi-chiba",       ja: "西千葉" },
  { id: "inage",             ja: "稲毛" },
  { id: "shin-kemigawa",     ja: "新検見川" },
  { id: "makuhari",          ja: "幕張" },
  { id: "makuhari-hongo",    ja: "幕張本郷" },
  { id: "tsudanuma",         ja: "津田沼" },
  { id: "higashi-funabashi", ja: "東船橋" },
  { id: "funabashi",         ja: "船橋" },
  { id: "nishi-funabashi",   ja: "西船橋" },
  { id: "ichikawa",          ja: "市川" },
  { id: "hon-yawata",        ja: "本八幡" },
  { id: "koiwa",             ja: "小岩" },
  { id: "shin-koiwa",        ja: "新小岩" },
  { id: "hirai",             ja: "平井" },
  { id: "kameido",           ja: "亀戸" },
  { id: "kinshicho",         ja: "錦糸町" },
  { id: "ryogoku",           ja: "両国" },
  { id: "asakusabashi",      ja: "浅草橋" },
  { id: "akihabara",         ja: "秋葉原" },
];

// station:最寄り駅 walk:徒歩分 exchange:交換率 hp:公式HP
// pworld:p-worldパス daidata:台データオンラインID
// hours:営業時間 p_total:パチンコ台数 s_total:スロット台数
const SHOPS = {
  // ===== 千葉エリア =====
  "ピーアーク千葉駅前店":        { station:"千葉",    walk:1,  exchange:"", hp:"", pworld:"chiba/p-ark-chiba2",       daidata:"100856", specialty:[], events:[], hours:"10:00〜22:40", p_total:"701",  s_total:"696"  },
  "アミューズ千葉":              { station:"千葉",    walk:5,  exchange:"", hp:"", pworld:"chiba/amuse",               daidata:"100711", specialty:[], events:[], hours:"10:00〜22:40", p_total:"616",  s_total:"509"  },
  "キクヤ千葉店":                { station:"千葉",    walk:5,  exchange:"", hp:"", pworld:"chiba/kikuya-chiba",        daidata:"101340", specialty:[], events:[], hours:"10:00〜22:45", p_total:"",     s_total:""     },
  "やすだ稲毛駅前店":            { station:"稲毛",    walk:1,  exchange:"", hp:"", pworld:"chiba/yasuda-inage",        daidata:"203061", specialty:[], events:[], hours:"09:50〜24:00", p_total:"",     s_total:""     },
  "エスパス日拓稲毛駅前新館":    { station:"稲毛",    walk:1,  exchange:"", hp:"", pworld:"chiba/espace2",             daidata:"100948", specialty:[], events:[], hours:"10:00〜23:00", p_total:"283",  s_total:"226"  },
  "パールショップともえ稲毛長沼店":{ station:"稲毛",  walk:10, exchange:"", hp:"", pworld:"chiba/tomoe-inage",         daidata:"",       specialty:[], events:[], hours:"10:00〜22:40", p_total:"",     s_total:""     },
  "パラッツォ新検見川店":        { station:"新検見川", walk:3, exchange:"", hp:"", pworld:"chiba/fplaza-shin",         daidata:"100957", specialty:[], events:[], hours:"10:00〜22:45", p_total:"",     s_total:""     },
  "やすだ幕張店":                { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"chiba/yasuda-makuhari",     daidata:"203072", specialty:[], events:[], hours:"10:00〜23:00", p_total:"",     s_total:""     },
  "TOHO幕張店":                  { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"chiba/toho-m",              daidata:"203071", specialty:[], events:[], hours:"10:00〜22:45", p_total:"200",  s_total:"116"  },
  "アスワン幕張":                { station:"幕張",    walk:5,  exchange:"", hp:"", pworld:"chiba/asuwan-m",            daidata:"203111", specialty:[], events:[], hours:"10:00〜22:45", p_total:"842",  s_total:"567"  },
  "ビックマーチ東習志野店":      { station:"幕張本郷", walk:10, exchange:"", hp:"", pworld:"chiba/bigmarch-narashino", daidata:"",       specialty:[], events:[], hours:"10:00〜23:00", p_total:"",     s_total:""     },
  "PIA津田沼":                   { station:"津田沼",  walk:3,  exchange:"", hp:"", pworld:"chiba/pia-tsudanuma",       daidata:"203014", specialty:[], events:[], hours:"10:00〜22:45", p_total:"475",  s_total:"636"  },
  "ニュークラウン津田沼店":      { station:"津田沼",  walk:5,  exchange:"", hp:"", pworld:"chiba/new-crown",           daidata:"203012", specialty:[], events:[], hours:"10:00〜22:45", p_total:"129",  s_total:"109"  },
  "ミリオン習志野店":            { station:"津田沼",  walk:10, exchange:"", hp:"", pworld:"chiba/million-narashino",   daidata:"203131", specialty:[], events:[], hours:"10:00〜22:45", p_total:"400",  s_total:"338"  },
  "パラッツォ船橋店":            { station:"船橋",    walk:3,  exchange:"", hp:"", pworld:"chiba/palazzo-funabashi",   daidata:"100815", specialty:[], events:[], hours:"10:00〜22:45", p_total:"684",  s_total:"466"  },
  "第一プラザ船橋店":            { station:"船橋",    walk:5,  exchange:"", hp:"", pworld:"chiba/d-plaza-funabashi",   daidata:"",       specialty:[], events:[], hours:"10:00〜22:50", p_total:"240",  s_total:"240"  },
  "アスワンFUNABASHI":           { station:"船橋",    walk:3,  exchange:"", hp:"", pworld:"chiba/aswan-f",             daidata:"203122", specialty:[], events:[], hours:"10:00〜23:00", p_total:"332",  s_total:"143"  },
  "トワーズ船橋店":              { station:"船橋",    walk:5,  exchange:"", hp:"", pworld:"chiba/towars-funabashi",    daidata:"203136", specialty:[], events:[], hours:"10:00〜22:45", p_total:"384",  s_total:"320"  },
  "ガイア西船橋店":              { station:"西船橋",  walk:3,  exchange:"", hp:"", pworld:"chiba/gaia-funabashi",      daidata:"203145", specialty:[], events:[], hours:"10:00〜22:45", p_total:"460",  s_total:"546"  },
  "西船スターダスト":            { station:"西船橋",  walk:5,  exchange:"", hp:"", pworld:"chiba/nishifuna-stardust",  daidata:"101371", specialty:[], events:[], hours:"10:00〜22:45", p_total:"207",  s_total:"46"   },
  "サンパレス本八幡":            { station:"本八幡",  walk:5,  exchange:"", hp:"", pworld:"chiba/sanpalace",           daidata:"202999", specialty:[], events:[], hours:"10:00〜22:45", p_total:"192",  s_total:"127"  },
  "本八幡UNO":                   { station:"本八幡",  walk:3,  exchange:"", hp:"", pworld:"chiba/1120uno",             daidata:"203003", specialty:[], events:[], hours:"10:00〜22:45", p_total:"585",  s_total:"526"  },
  "本八幡ZoRoN":                 { station:"本八幡",  walk:5,  exchange:"", hp:"", pworld:"chiba/1122zoron",           daidata:"210248", specialty:[], events:[], hours:"10:00〜22:45", p_total:"234",  s_total:"161"  },
  "サンラッキー市川店":          { station:"市川",    walk:5,  exchange:"", hp:"", pworld:"chiba/jb-shopitikawa",      daidata:"202984", specialty:[], events:[], hours:"10:00〜22:45", p_total:"520",  s_total:"337"  },
  "ハップス市川駅前店":          { station:"市川",    walk:1,  exchange:"", hp:"", pworld:"chiba/haps-ichieki",        daidata:"202990", specialty:[], events:[], hours:"10:00〜22:50", p_total:"244",  s_total:"260"  },
  "ニュー後楽園市川店":          { station:"市川",    walk:5,  exchange:"", hp:"", pworld:"chiba/new-kourakuen-i",     daidata:"202989", specialty:[], events:[], hours:"10:00〜23:00", p_total:"346",  s_total:"187"  },
  // ===== 東京エリア（総武線） =====
  "Dステーション新小岩":         { station:"新小岩",  walk:3,  exchange:"", hp:"", pworld:"tokyo/dstation-shinkoiwa",  daidata:"",       specialty:[], events:[], hours:"10:00〜22:45", p_total:"",     s_total:""     },
  "エスパス1300新小岩北口駅前店":{ station:"新小岩",  walk:1,  exchange:"", hp:"", pworld:"tokyo/espace-shinkoiwa39",  daidata:"100260", specialty:[], events:[], hours:"10:00〜22:40", p_total:"",     s_total:""     },
  "プライム平井":                { station:"平井",    walk:3,  exchange:"", hp:"", pworld:"tokyo/prime-hirai",         daidata:"101191", specialty:[], events:[], hours:"10:00〜22:55", p_total:"",     s_total:""     },
  "キコーナ平井店":              { station:"平井",    walk:3,  exchange:"", hp:"", pworld:"tokyo/kicona-hirai",        daidata:"203374", specialty:[], events:[], hours:"10:00〜22:45", p_total:"382",  s_total:"347"  },
  "新ガーデン亀戸店":            { station:"亀戸",    walk:3,  exchange:"", hp:"", pworld:"tokyo/garden-kameido",      daidata:"203379", specialty:[], events:[], hours:"10:00〜23:00", p_total:"",     s_total:""     },
  "スパークル亀戸店":            { station:"亀戸",    walk:5,  exchange:"", hp:"", pworld:"tokyo/sparkle",             daidata:"203383", specialty:[], events:[], hours:"10:00〜23:00", p_total:"190",  s_total:"193"  },
  "スーパーDステーション錦糸町": { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"tokyo/dstation-kinshicho",  daidata:"",       specialty:[], events:[], hours:"10:00〜22:45", p_total:"639",  s_total:"361"  },
  "みとやジャックポット錦糸町店":{ station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"tokyo/mitoya-jackpot",      daidata:"204071", specialty:[], events:[], hours:"10:00〜22:50", p_total:"176",  s_total:"47"   },
  "みとや錦糸町南口店":          { station:"錦糸町",  walk:1,  exchange:"", hp:"", pworld:"tokyo/mitoyakinsityominami", daidata:"101388", specialty:[], events:[], hours:"10:00〜22:50", p_total:"",     s_total:""     },
  "ヒノマル錦糸町店":            { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"tokyo/hinomaru-kinshicho",  daidata:"204070", specialty:[], events:[], hours:"10:00〜22:40", p_total:"",     s_total:""     },
  "ヒノマル錦糸町店II":          { station:"錦糸町",  walk:3,  exchange:"", hp:"", pworld:"tokyo/hinomaru-kinshicho2", daidata:"204072", specialty:[], events:[], hours:"10:00〜22:40", p_total:"328",  s_total:"86"   },
  "ビッグアップル秋葉原店":      { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/big-apple",           daidata:"203631", specialty:[], events:[], hours:"10:00〜22:40", p_total:"185",  s_total:"675"  },
  "アイランド秋葉原店":          { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/island",              daidata:"203632", specialty:[], events:[], hours:"10:00〜22:40", p_total:"",     s_total:""     },
  "秋葉原UNO":                   { station:"秋葉原",  walk:3,  exchange:"", hp:"", pworld:"tokyo/2090uno",             daidata:"203634", specialty:[], events:[], hours:"10:00〜22:45", p_total:"",     s_total:""     },
  "エスパス日拓秋葉原駅前店":    { station:"秋葉原",  walk:1,  exchange:"", hp:"", pworld:"tokyo/espace-akb",          daidata:"100928", specialty:[], events:[], hours:"10:00〜23:00", p_total:"327",  s_total:"522"  },
  "サイバーパチンコ秋葉原昭和通り口店":{ station:"秋葉原", walk:3, exchange:"", hp:"", pworld:"tokyo/cy-akihabara",    daidata:"203636", specialty:[], events:[], hours:"10:00〜22:50", p_total:"303",  s_total:"308"  },
};

const DATA = {
  tokyo: {
    d1: ["秋葉原UNO"],
    d2: ["ビッグアップル秋葉原店","新ガーデン亀戸店"],
    d3: ["Dステーション新小岩","エスパス1300新小岩北口駅前店","キコーナ平井店","サイバーパチンコ秋葉原昭和通り口店","スーパーDステーション錦糸町"],
    d4: ["みとやジャックポット錦糸町店","みとや錦糸町南口店"],
    d5: [],
    d6: ["アイランド秋葉原店","エスパス日拓秋葉原駅前店","ビッグアップル秋葉原店"],
    d7: ["エスパス1300新小岩北口駅前店","エスパス日拓秋葉原駅前店","スパークル亀戸店","みとやジャックポット錦糸町店","みとや錦糸町南口店","秋葉原UNO"],
    d8: ["新ガーデン亀戸店"],
    d9: ["Dステーション新小岩","エスパス1300新小岩北口駅前店","キコーナ平井店","スーパーDステーション錦糸町"],
    d0: ["キコーナ平井店","ヒノマル錦糸町店","ヒノマル錦糸町店II","みとやジャックポット錦糸町店","みとや錦糸町南口店","新ガーデン亀戸店"],
    m1:[],m2:[],m3:[],m4:[],m5:[],m6:[],m7:[],m8:[],m9:[],m10:[],m11:[],m12:[],m13:[],m14:[],m15:[],m16:[],m17:[],m18:[],m19:[],m20:[],m21:[],m22:[],m23:[],m24:[],m25:[],m26:[],m27:[],m28:[],m29:[],m30:[],m31:[],
    w0:[],w1:[],w2:[],w3:[],w4:[],w5:[],
    w6: ["新ガーデン亀戸店"],
    nth_1_6:[],nth_2_6:[],nth_3_6:[],nth_4_6:[],nth_1_0:[],nth_2_0:[],nth_3_0:[],nth_1_1:[],nth_2_1:[],nth_3_1:[],nth_1_2:[],nth_2_2:[],nth_3_2:[],nth_1_3:[],nth_2_3:[],nth_3_3:[],nth_1_4:[],nth_2_4:[],nth_3_4:[],nth_1_5:[],nth_2_5:[],nth_3_5:[],
    last_0:[],last_1:[],last_2:[],last_3:[],last_4:[],last_5:[],last_6:[],
    zorome: ["アイランド秋葉原店","ビッグアップル秋葉原店"],
    md: ["アイランド秋葉原店","エスパス日拓秋葉原駅前店","ビッグアップル秋葉原店","新ガーデン亀戸店"]
  },
  chiba: {
    d1: ["アスワン幕張","アミューズ千葉","第一プラザ船橋店","本八幡UNO"],
    d2: ["パールショップともえ稲毛長沼店","パラッツォ新検見川店","パラッツォ船橋店"],
    d3: ["ガイア西船橋店","サンパレス本八幡","ビックマーチ東習志野店","ミリオン習志野店","やすだ幕張店"],
    d4: ["TOHO幕張店"],
    d5: ["PIA津田沼","ピーアーク千葉駅前店","やすだ稲毛駅前店","やすだ幕張店","ニュー後楽園市川店"],
    d6: ["トワーズ船橋店","パールショップともえ稲毛長沼店"],
    d7: ["PIA津田沼","アスワンFUNABASHI","アミューズ千葉","エスパス日拓稲毛駅前新館","キクヤ千葉店","やすだ幕張店","やすだ稲毛駅前店","西船スターダスト"],
    d8: ["ハップス市川駅前店","パラッツォ新検見川店","パラッツォ船橋店"],
    d9: ["ガイア西船橋店","ビックマーチ東習志野店","やすだ幕張店"],
    d0: [],
    m1: ["サンラッキー市川店"],
    m2:[],m3:[],m4:[],m5:[],m6:[],m7:[],m8:[],m9:[],m10:[],
    m11: ["PIA津田沼","第一プラザ船橋店"],
    m12: ["PIA津田沼"],
    m13:[],
    m14: ["TOHO幕張店"],
    m15:[],m16:[],m17:[],m18:[],m19:[],m20:[],
    m21: ["サンラッキー市川店","やすだ稲毛駅前店","やすだ幕張店","第一プラザ船橋店"],
    m22: ["やすだ稲毛駅前店","やすだ幕張店"],
    m23:[],m24:[],m25:[],m26:[],
    m27: ["ニュークラウン津田沼店"],
    m28:[],m29:[],m30:[],m31:[],
    w0:[],w1:[],w2:[],w3:[],w4:[],w5:[],w6:[],
    nth_1_6:[],nth_2_6:[],nth_3_2:[],nth_3_6:[],
    nth_1_0:[],nth_2_0:[],nth_3_0:[],nth_1_1:[],nth_2_1:[],nth_3_1:[],nth_1_3:[],nth_2_3:[],nth_3_3:[],nth_1_4:[],nth_2_4:[],nth_3_4:[],nth_1_5:[],nth_2_5:[],nth_3_5:[],nth_4_6:[],
    last_6:[],last_0:[],last_1:[],last_2:[],last_3:[],last_4:[],last_5:[],
    zorome: ["PIA津田沼","アスワン幕張","アミューズ千葉","エスパス日拓稲毛駅前新館","サンラッキー市川店","トワーズ船橋店"],
    md: ["PIA津田沼","アミューズ千葉","キクヤ千葉店","本八幡ZoRoN"]
  }
};
